export default function Head(){
    return(
        <>
            <title>NETFILMS❤️</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta name="description" content="Generated by create next app and made with Furkan Baştan." />
            <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        </>
    )
}   